name: project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  google_sign_in: ^5.2.4
  image_picker: ^0.8.4+10
  intl: ^0.17.0
  introduction_screen: ^3.0.0
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
